services:
  spotalert-webapp:
    build: .
    container_name: spotalert-webapp
    restart: unless-stopped
    ports:
      - "7478:8088"
    volumes:
      - /Volume2/public/docker/spotalert-webapp/config:/app/config
      - /Volume2/public/docker/spotalert-webapp/lightroom:/app/lightroom
      - /Volume2/public/docker/spotalert-webapp/logs:/app/logs
      - /Volume2/public/docker/spotalert-webapp/static:/app/static
    environment:
      - TZ=Australia/Sydney
