services:
  spotalert:
    build: .
    container_name: spotalert
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /Volume2/public/docker/spotalert/config:/app/config
      - /Volume2/public/docker/spotalert/lightroom:/app/lightroom
      - /Volume2/public/docker/spotalert/logs:/app/logs
    environment:
      - TZ=Australia/Sydney
